print("WARKOP 'warung kopi' ")
print("Pilihan Menu : ")
print("1. Kopi Hitam -> Rp.8.000")
print("2. Kopi Susu -> Rp. 10.000")
print("3. Es kopi coklat susu Rp -> Rp.12.000")
print("4. Es Coklat gula aren -> Rp.12.000")
print("5. Tahu Krispy -> Rp.5.000")
print("6. Bakwan -> Rp.5.000")
print("7. Kentang Goreng -> Rp.5.000")
menu = int(input("Menu yang anda pilih: "))
if menu == 1:
    nama = str(input("Masukkan nama anda: "))
    print("Kopi Hitam -> Rp.8.000")
    jumlah = int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total = jumlah*8000
    print("---------------------")
    print("halo", nama)
    print("Kopi Hitam", jumlah ,"bungkus")
    print("Total pesan anda Rp.",total)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
elif menu == 2:
    nama = str(input("Masukkan nama anda: "))
    print("Kopi Susu -> Rp. 10.000")
    jumlah2= int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total2 = jumlah2*10000
    print("---------------------")
    print("halo", nama)
    print("Kopi Susu", jumlah2 ,"bungkus")
    print("Total pesan anda Rp.",total2)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
elif menu == 3:
    nama = str(input("Masukkan nama anda: "))
    print("Es kopi coklat susu Rp -> Rp.12.000")
    jumlah3= int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total3 = jumlah3*12000
    print("---------------------")
    print("halo", nama)
    print("Es Kopi Coklat Susu", jumlah3 ,"bungkus")
    print("Total pesan anda Rp.",total3)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
elif menu == 4:
    nama = str(input("Masukkan nama anda: "))
    print("Es Coklat gula aren -> Rp.12.000")
    jumlah4 = int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total4 = jumlah4*12000
    print("---------------------")
    print("halo", nama)
    print("Es Coklat Gula Aren", jumlah4 ,"bungkus")
    print("Total pesan anda Rp.",total4)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
elif menu == 5:
    nama = str(input("Masukkan nama anda: "))
    print("Tahu Krispy -> Rp.5.000")
    jumlah5 = int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total5 = jumlah5*5000
    print("---------------------")
    print("halo", nama)
    print("Tahu Krispy", jumlah5 ,"bungkus")
    print("Total pesan anda Rp.",total5)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
elif menu == 6:
    nama = str(input("Masukkan nama anda: "))
    print("Bakwan -> Rp.5.000")
    jumlah6 = int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total6 = jumlah6*5000
    print("---------------------")
    print("halo", nama)
    print("Bakwan", jumlah6 ,"bungkus")
    print("Total pesan anda Rp.",total6)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
elif menu == 7:
    nama = str(input("Masukkan nama anda: "))
    print("Kentang Goreng -> Rp.5.000")
    jumlah7 = int(input("Anda ingin pesan berapa ?"))
    print("---------------------")
    print("Pesanan anda sedang di proses")
    print("Mohon tunggu sebentar!")
    total7 = jumlah7*5000
    print("---------------------")
    print("halo", nama)
    print("Kentang goreng", jumlah7 ,"bungkus")
    print("Total pesan anda Rp.",total7)
    print("***TERIMAKASIH***")
    print("***WARKOP***")
else:
    print("Menu yang anda inginkan tidak ada di sini")


